export const FETCH_COLLECTION_DATA_PENDING = 'FETCH_COLLECTION_DATA_PENDING';
export const FETCH_COLLECTION_DATA_SUCCESS = 'FETCH_COLLECTION_DATA_SUCCESS';
export const FETCH_COLLECTION_DATA_ERROR = 'FETCH_COLLECTION_DATA_ERROR';
export const FETCH_COLLECTION_PHOTOS_PENDING =
  'FETCH_COLLECTION_PHOTOS_PENDING';
export const FETCH_COLLECTION_PHOTOS_SUCCESS =
  'FETCH_COLLECTION_PHOTOS_SUCCESS';
export const FETCH_COLLECTION_PHOTOS_NO_MORE_DATA =
  'FETCH_COLLECTION_PHOTOS_NO_MORE_DATA';
export const FETCH_COLLECTION_PHOTOS_ERROR = 'FETCH_COLLECTION_PHOTOS_ERROR';
export const FETCH_MORE_COLLECTION_PHOTOS = 'FETCH_MORE_COLLECTION_PHOTOS';
export const OPEN_PHOTO_MODAL = 'OPEN_PHOTO_MODAL';
export const CLOSE_PHOTO_MODAL = 'CLOSE_PHOTO_MODAL';
export const getPageToLoad = state => state.collection.pageToLoad;
